### ISSUE TITLE
Check code for not allowed functions

### ISSUE THREAD

**Issue by skrtks** [skrtks/webserv#29]

**Comment by pde-bakk** [comment]
saw perror() in the code, its not allowed. didnt fix it yet cus im working in a different (bonus) branch

**Comment by skrtks** [comment]
> saw perror() in the code, its not allowed. didnt fix it yet cus im working in a different (bonus) branch

@tuan9999 could you look at that? It's on L200 in handleAutoIndex.

**Comment by skrtks** [comment]
I also found *#include	<set>* in Connection.hpp, that's not in the allowed includes list
